version: '3.4'
services:
  learning-rails_setup:
    build:
      context: .
      network: host
    depends_on:
      - postgres
    environment:
      - PASSENGER_APP_ENV=development
    entrypoint: ./setup.sh
  learning-rails:
    container_name: learning-rails
    build:
      context: .
      network: host
    depends_on:
      - postgres
      - learning-rails_setup
    environment:
      - PASSENGER_APP_ENV=development
    ports:
      - "80:80"
    volumes:
      - .:/home/yagdra/labs/learning-rails
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=webapp
      - POSTGRES_DB=webapp_development
    ports:
      - '5432:5432'
    volumes:
      - postgres_data
  postgres_data:
    image: postgres
    volumes:
      - /home/yagdra/labs/learning-rails_DB:/var/lib/postgresql/data
    command: /bin/true
